// Generated by Wrangler on Wed Jun 19 2024 12:00:06 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types --env-interface CloudflareBindings --env prod`

interface CloudflareBindings {
	ENVIRONMENT: string;
	CLIENT_ID: string;
	CLIENT_SECRET: string;
	DB: D1Database;
	AI: Ai;
}
